Feature refactor code
Knine69/springRest_task pull request #2
Opened 2022-10-28 13:53 UTC by Knine69

Managed exception handling, new exceptions, refactored controllers and addition of new models to database as well as business logic refactoring

2022-10-31 10:04 UTC, Pokemon3108 requested changes

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
> +    private final PageResponse pageResponse = new PageResponse();
Why don't you use @Autowired?

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
> +    public GiftCertificate get(@PathVariable String id) throws IdNotFound, InvalidInputInformation {
You can pass Integer as a param. Spring will convert it under the hood. That's you will not need Integer.parseInt

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
> +    public Order placeNewOrder(@RequestParam List<Integer> certID,
certID as a name of variable does'nt match Java code convention

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
> +            , @RequestBody Map<String, Object> patch) throws IdNotFound, InvalidInputInformation {
Not pretty formatting

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
>      public GiftCertificate update(@PathVariable("certId") String id
String id -> Integer id (mentioned above)

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/UserController.java
> +    @ResponseBody
It's not obligatory to put @ResponseBody if we marked class as @RestController

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/UserController.java
> +    public Order getOrder(@PathVariable(name = "userID") String userID,
java code convention

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/models/GiftCertificate.java
> +    public GiftCertificate(int id, String name, String description, BigDecimal price, int duration,
How about using @Builder instead of such big constructor?

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/UserService.java
> +    Order getOrder(int userID, int orderID) throws IdNotFound, OrderNotRelated;
java code convention

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +    private void saveClearing(GiftCertificate certificate) {
What does it mean? 'saveClearing'. Please, rename, looks misunderstandable

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +                    throw new IdAlreadyInUse();
Why do you throw exception, catch it and rethrow RuntimeException?

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +                validateNegative(t.getId());
It's not ok to throw RunTimeException. You can get rid of lambda expression and use simple foreach cycle and highlight, that your method throws exception with word '**throws**'

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +        certID.forEach(id -> {
The same (about throwing RunTimeException) described above

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/UserServiceImp.java
> +public class UserServiceImp implements UserService {
typo (UserServiceImp**l**)

2022-10-31 10:04 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/UserServiceImp.java
> +    public Tag mostUsedTag() throws IdNotFound, NoExistingOrders, NoTagInOrder {
The complexity of method is high. Can you split the whole logic into small private methods?

2022-10-31 10:04 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateControllerTest.java
> +    void getReturnOne() throws IdNotFound, InvalidInputInformation {
Please, describe what your test do, what they check. The name of test should be like 'checkThatOneTagIsFoundIf...'

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateController.java
> +                               @PathVariable(name = "userID") int userID) throws IdNotFound {
java code convention

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/models/Order.java
> +        this.certificates.forEach(c -> this.cost = this.cost.add(new BigDecimal(c.getPrice().toString())));
beautify formatting, please

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/UserService.java
> +    Tag mostUsedTag() throws IdNotFound, NoExistingOrders, NoTagInOrder;
Probably it's better to move to TagService, isnt it?

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +        for (Tag t : certificate.getAssociatedTags()) {
Move it to separate method, like "validate(Tag tag)". It can be even if tagService

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/GiftCertificateServiceImpl.java
> +        validateNegative(certificate.getDuration());
move to validate(GitCertificate certificate)

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/UserServiceImpl.java
> +    public Order getOrder(int userID, int orderID) throws IdNotFound, OrderNotRelated {
java code convention

2022-11-02 18:07 UTC, Pokemon3108 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/impl/UserServiceImpl.java
> +    private Integer getMaxTagID(Map<Integer, Integer> tags) {
java code convention

2022-11-02 18:07 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateControllerTest.java
> +    private static final OrderRepository orderRepository = Mockito.mock(OrderRepository.class);
There is a special annotation @Mock. And you don't need to write Mockito.mock(...). Read about it)

2022-11-02 18:07 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateControllerTest.java
> +    private final GiftCertificateController controller = new GiftCertificateController(pageResponse, giftCertificateService);
Read about @InjectMocks. It suits here.

2022-11-02 18:07 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateControllerTest.java
> +    void updateGiftCertificateIDNotFound() {
java code convention

2022-11-02 18:07 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/controller/GiftCertificateControllerTest.java
> +    void deleteGiftCertificateIDNotFound() {
java code convention

2022-11-02 18:07 UTC, Pokemon3108 commented on src/test/java/com/jhuguet/sb_taskv1/app/services/impl/TagServiceImplTest.java
> +    void getTagIfGivenIdIsExistent() throws IdNotFound {
IsExistent to exists

2022-11-03 17:16 UTC, Knine69 commented on src/main/java/com/jhuguet/sb_taskv1/app/services/UserService.java
> +    Tag mostUsedTag() throws IdNotFound, NoExistingOrders, NoTagInOrder;
It should return the most used tag of the user with the highest order cost. Taking this into account, maybe it should be renamed? Or do you still consider it is better to be moved?

2022-11-04 16:15 UTC, merged